# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: install hg
        run: |
          set -xe
          # wget https://www.mercurial-scm.org/release/mercurial-3.2.4.tar.gz
          # tar zxf mercurial-3.2.4.tar.gz
          # cd mercurial-3.2.4
          # sudo pip install docutils
          # sudo make install
          sudo pip install mercurial==5.3.2

      - name: install git-remote-hg
        run: |
          set -xe
          git clone git@github.com:mozillazg/git-remote-hg.git -b pypy
          cd git-remote-hg
          git chmod +x git-remote-hg
          cp git-remote-hg /usr/local/bin/
          
      - name: init mirror repo
        run: |
          set -xe
          git clone "hg::https://foss.heptapod.net/pypy/buildbot"
          cd buildbot
          git config core.notesRef refs/notes/hg
          git remote add mirror git@github.com:mozillazg/pypy-buildbot.git
          
          for remote in `git branch|grep -v '\* master'`; do
            git branch -d $remote
          done
          
          python ../git-remote-hg/track_all_remote_branches.py
          
          git pull
          git reset --hard default
          
          git push mirror --all
          
          git push mirror --tags
