name: mirror

on:
  workflow_dispatch:
  schedule:
    - cron: "03 */8 * * *"


jobs:

  mirror-buildbot:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: mirror https://foss.heptapod.net/pypy/buildbot to https://github.com/mozillazg/pypy-buildbot
        uses: 'mozillazg/mirror-hg-repo@v2'
        with:
          source-hg-repo-url: 'https://foss.heptapod.net/pypy/buildbot'
          destination-git-repo-owner: 'mozillazg'
          destination-git-repo-name: 'pypy-buildbot'
          destination-git-personal-token: '${{ secrets.PERSONAL_GIT_TOKEN }}'

  mirror-cffi:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: mirror https://foss.heptapod.net/pypy/cffi to https://github.com/mozillazg/cffi
        uses: 'mozillazg/mirror-hg-repo@v2'
        with:
          source-hg-repo-url: 'https://foss.heptapod.net/pypy/cffi'
          destination-git-repo-owner: 'mozillazg'
          destination-git-repo-name: 'cffi'
          destination-git-personal-token: '${{ secrets.PERSONAL_GIT_TOKEN }}'

#   mirror-pypy:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read
#   
#     steps:
#       - uses: actions/checkout@v4
#       - uses: actions/setup-python@v5
#         with:
#           python-version: '3.10'
#   
#       - name: mirror https://foss.heptapod.net/pypy/pypy to https://github.com/mozillazg/pypy
#         uses: 'mozillazg/mirror-hg-repo@v2'
#         with:
#           source-hg-repo-url: 'https://foss.heptapod.net/pypy/pypy'
#           destination-git-repo-owner: 'mozillazg'
#           destination-git-repo-name: 'pypy'
#           destination-git-personal-token: '${{ secrets.PERSONAL_GIT_TOKEN }}'
#           repo-style: 'pypy-style'

  mirror-freenginx:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: mirror https://freenginx.org/hg/nginx to https://github.com/freenginx-mirror/nginx
        uses: 'mozillazg/mirror-hg-repo@v2'
        with:
          source-hg-repo-url: 'https://freenginx.org/hg/nginx'
          destination-git-repo-owner: 'freenginx-mirror'
          destination-git-repo-name: 'nginx'
          destination-git-personal-token: '${{ secrets.PERSONAL_GIT_TOKEN }}'

      - name: mirror https://freenginx.org/hg/xslscript to https://github.com/freenginx-mirror/xslscript
        uses: 'mozillazg/mirror-hg-repo@v2'
        with:
          source-hg-repo-url: 'https://freenginx.org/hg/xslscript'
          destination-git-repo-owner: 'freenginx-mirror'
          destination-git-repo-name: 'xslscript'
          destination-git-personal-token: '${{ secrets.PERSONAL_GIT_TOKEN }}'

      - name: mirror https://freenginx.org/hg/nginx-tests to https://github.com/freenginx-mirror/nginx-tests
        uses: 'mozillazg/mirror-hg-repo@v2'
        with:
          source-hg-repo-url: 'https://freenginx.org/hg/nginx-tests'
          destination-git-repo-owner: 'freenginx-mirror'
          destination-git-repo-name: 'nginx-tests'
          destination-git-personal-token: '${{ secrets.PERSONAL_GIT_TOKEN }}'

      - name: mirror https://freenginx.org/hg/nginx-site to https://github.com/freenginx-mirror/nginx-site
        uses: 'mozillazg/mirror-hg-repo@v2'
        with:
          source-hg-repo-url: 'https://freenginx.org/hg/nginx-site'
          destination-git-repo-owner: 'freenginx-mirror'
          destination-git-repo-name: 'nginx-site'
          destination-git-personal-token: '${{ secrets.PERSONAL_GIT_TOKEN }}'
